apps/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from apps.blog import views


urlpatterns = [
		url(r'^$', views.BlogListView.as_view(), name="home"),
		url(r'^(?P<pk>\d+)/(?P<blog_link>[\w,-]*)$', views.BlogDetailView.as_view(), name='blog_detail'),
               ]

apps/wedding/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from apps.wedding import views  

urlpatterns = [
		url(r'^$', views.index),
		url(r'^add_comments/', views.add_comments),
			]

django_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django_blog.sitemaps import BlogSitemap
from django.http import HttpResponse
from apps.blog import views

admin.autodiscover()

sitemaps = {
    'blog': BlogSitemap,
}

urlpatterns = [
        url(r'^about$', views.about, name='about'),
        url(r'^', include('apps.blog.urls', namespace='blog')),
        url(r'^blog/', include('apps.blog.urls', namespace='blog')),
        url(r'^wedding/', include('apps.wedding.urls', namespace='wedding')),
        url(r'^admin/', include(admin.site.urls)),
        url(r'404', views.not_found),
        url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
           name='django.contrib.sitemaps.views.sitemap'),
        url(r'^robots.txt/$',
           lambda r: HttpResponse("User-agent: *\nDisallow: /admin/\nSitemap: <http://simplecode.in/sitemap.xml>", content_type="text/plain")),
        url(r'^rss/', views.LatestPosts(), name='feeds')
      ]

urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django_blog.sitemaps import BlogSitemap
from django.http import HttpResponse
from apps.blog import views

admin.autodiscover()

sitemaps = {
    'blog': BlogSitemap,
}

urlpatterns = [
        url(r'^about$', views.about, name='about'),
        url(r'^blog/', include('apps.blog.urls', namespace='blog')),
        url(r'^$', include('apps.blog.urls', namespace='blog')),
        url(r'^wedding/', include('apps.wedding.urls', namespace='wedding')),
        url(r'^admin/', include(admin.site.urls)),
        url(r'404', views.not_found),
        url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
           name='django.contrib.sitemaps.views.sitemap'),
        url(r'^robots.txt$',
           lambda r: HttpResponse("User-agent: *\nDisallow: /admin/\nSitemap: <http://simplecode.in/sitemap.xml>", content_type="text/plain")),
        url(r'^rss/', views.LatestPosts(), name='feeds')
      ]

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse


class Blog(models.Model):
    STATUS_CHOICES = (
        ('d', "draft"),
        ('p', "release"),
    )

    title = models.CharField('Title', max_length=150, db_index=True, unique=True)
    link = models.CharField('Link', max_length=150, default='')
    link.help_text = "Cool URIs don't change"
    snippet = models.CharField('Summary', max_length=500, default='')
    content = models.TextField('Content', )

    add_time = models.DateTimeField('Created', auto_now_add=True)
    publish_time = models.DateTimeField('Issuing Time', null=True)
    update_time = models.DateTimeField('Change the time', auto_now=True)
    status = models.CharField('Status', max_length=1, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])

    is_public = models.BooleanField('Public', default=True)
    is_top = models.BooleanField('Sticky', default=False)
    access_count = models.IntegerField('Pageviews', default=1, editable=False)
    category = models.ForeignKey('Category', verbose_name='category')
    tags = models.ManyToManyField('Tag', verbose_name='Label collection', null=True, blank=True)
    tags.help_text = ''
    author = models.ForeignKey(User, verbose_name='Author')

    def save(self, *args, **kwargs):
        self.link = slugify(self.link)
        self.snippet = self.snippet or self.content[:140]
        super(Blog, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:blog_detail', args=(self.id, self.link))

    def __str__(self):
        return self.title


class Category(models.Model):

    title = models.CharField('Name', max_length=50, db_index=True, unique=True)

    class Meta:
        ordering = ['title', ]

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField('Name', max_length=50, db_index=True, unique=True)

    def __str__(self):
        return self.title

apps/wedding/models.py
from django.db import models


# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    body = models.CharField(max_length=2000, blank=True)

    def __str__(self):
        return ":".join([self.name, self.body[:100]])

apps/blog/forms.py
import datetime
from django import forms

from pagedown.widgets import AdminPagedownWidget


class BlogForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'size': 118}))
    content = forms.CharField(label='Content', widget=AdminPagedownWidget())
    snippet = forms.CharField(label='Summary',
                              widget=forms.Textarea(attrs={'cols': 85, 'rows': 7}),
                              required=False)
    def save(self, commit=True):
        instance = super(BlogForm, self).save(commit=False)
        if instance.status == 'p' and instance.publish_time is None:
            instance.publish_time = datetime.datetime.now()
        if commit:
            instance.save()
        return instance


apps/wedding/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'phone', 'body')

apps/blog/views.py
# -*- coding: utf-8 -*-
import random
from django.conf import settings
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.syndication.views import Feed
from .models import Blog



def about(request):
    return render(request, 'about.html')


def not_found(request):
    return render(request, '404.html', {})


class BlogListView(ListView):
    model = Blog
    queryset = Blog.objects.filter(status='p', is_public=True)
    template_name = 'post_list.html'
    paginate_by = settings.PAGE_SIZE
    ordering = "-publish_time"
    context_object_name = "blogs"


class BlogDetailView(DetailView):
    model = Blog
    template_name = "post_detail.html"

    def get_object(self, queryset=None):
        blog = super(BlogDetailView, self).get_object(queryset)
        # 阅读数增1
        blog.access_count += 1
        blog.save()
        return blog

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        current_post = context.get("object")

        # 随机文章
        count = Blog.objects.filter(status='p', is_public=True).count()
        randint = random.randint(0, count)
        try:
            random_post = Blog.objects.filter(status='p', is_public=True)[randint:randint + 1][0]
        except IndexError:
            random_post = None
        try:
            next_post = Blog.objects.filter(pk__lt=current_post.id).order_by('-pk')[0]
        except IndexError:
            next_post = None

        context['next_post'] = next_post
        context['random_post'] = random_post
        return context


class LatestPosts(Feed):
    title = "simplecode"
    link = "/"

    def items(self):
        blogs = Blog.objects.filter(status='p', is_public=True).all().order_by('-publish_time')[:10]
        return blogs

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.snippet

apps/wedding/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from .forms import CommentForm
from .models import Comment
from django.shortcuts import redirect

def index(request):
    comments = Comment.objects.all()
    return render(request, "wedding_index.html", {"comments": comments})


def add_comments(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = CommentForm()

    return redirect("/wedding/")

apps/blog/templates/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block head %}
<header class="main-header post-head no-cover">
    {% include "widget/main-nav.html" %}
</header>
{% endblock %}
{% block body %}
<main class="content" role="main">
    <article class="post page">

        <header class="post-header">
            <h1 class="post-title">About</h1>
        </header>

        <section class="post-content">
            <h1 class="post-title">Side Projects</h1>
        </section>
        {% include "widget/disqus.html" %}
    </article>
</main>
{% endblock %}
    
 

apps/blog/templates/base.html
<!DOCTYPE html>
<html>
<head>

    {% load staticfiles %}
    {% load compress %}
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}"/>
    <meta name="HandheldFriendly" content="True"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://apps.bdimg.com/libs/highlight.js/9.1.0/styles/github.min.css">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    {% compress css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/screen.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/font.css' %}"/>
    {% endcompress %}
	
    <style>
        pre {
        word-wrap: normal;
        -moz-hyphens: none;
        -ms-hyphens: none;
        -webkit-hyphens: none;
        hyphens: none;
        font-size: 0.7em;
        line-height: 1.3em;
        }
        pre code, pre tt {
        white-space: pre;
        }
    </style>
</head>

<body class="{% block body_class %}{% endblock %} nav-closed">
<div class="nav">
    <h3 class="nav-title">Menu</h3>
    <a href="#" class="nav-close">
        <span class="hidden">Close</span>
    </a>
    <ul>
        <li class="nav-home nav-current" role="presentation"><a href="{% url 'blog:home' %}">Home</a></li>
        <li class="nav-about" role="presentation"><a href="{% url 'about' %}">About</a></li>
        <li class="nav-start-a-blog" role="presentation"><a href="">Github</a></li>
    </ul>
    <a class="subscribe-button icon-feed" href="{% url 'feeds'%}">Subscribe</a>
</div>
<span class="nav-cover"></span>

<div class="site-wrapper">

    {% block head %}{% endblock %}
    {% block body %}{% endblock %}

    <footer class="site-footer clearfix">
        <section class="copyright"><a href="http://simplecode.in">simplecode</a> &copy; 2015</section>
        <section class="poweredby">
            <strong>Made with <i class="fa fa-heart"></i> in India</strong>
        </section>

    </footer>

</div>

<script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>

{% compress js %}
<script type="text/javascript" src="{% static 'js/jquery.fitvids.js' %}"></script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-73612812-1', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->

{% endcompress %}

<!-- http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html -->
<script src="http://apps.bdimg.com/libs/highlight.js/9.1.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
<script id="dsq-count-scr" src="//simplisticcode.disqus.com/count.js" async></script>
</body>
</html>

apps/blog/templates/post_detail.html
{% extends "base.html" %}
{% load myapp_markup %}
{% block description %}{{blog.snippet | truncatewords:50}}{%endblock%}
{% block title %}{{blog.title}}{% endblock %}
{%block body_class %} post-template {% endblock %}
{% load staticfiles %}

{% block head %}
<header class="main-header post-head no-cover">
    {% include "widget/main-nav.html" %}
</header>
{% endblock %}


{% block body %}

<main class="content" role="main">
    <article class="post">

        <header class="post-header">
            <h2 class="post-title">{{blog.title}}</h2>
            <section class="post-meta">
                <time class="post-date" datetime="{{blog.add_time|date:'b d, Y'}}">{{blog.add_time|date:"b d, Y"}}
                </time>
                {% if blog.tags %}on
                {% for tag in blog.tags.all %}
                {{tag }}
                {% endfor %}
                {% endif %}
            </section>
        </header>

        <section class="post-content">
            {{blog.content | md1}}
        </section>
        <footer class="post-footer">

            <section class="author">
                <h4><a href="{{url}}">{{blog.author.username}}</a></h4>
                <p>I give as good as I get</p>
            </section>

        </footer>

        {% include "widget/disqus.html" %}
    </article>


</main>

    <aside class="read-next">
    <a class="read-next-story " href="{{next_post.get_absolute_url}}">
        <section class="post">
            <h2>{{next_post.title}}</h2>
        </section>
    </a>
    <a class="read-next-story prev "  href="{{random_post.get_absolute_url}}">
        <section class="post">
            <h2>{{random_post.title}}</h2>
        </section>
    </a>
</aside>

{% endblock %}

apps/blog/templates/post_list.html
{% extends "base.html" %}
{% load myapp_markup %}
{% block description %}Tech django java android blogs{%endblock%}
{% block title %}Simplecode{% endblock %}
{%block body_class %} home-template {% endblock %}
{% load staticfiles %}
{% block head %}

{% include "widget/main-nav.html" %}
<header class="main-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
    <div class="vertical">
        <div class="main-header-content inner">
            <h1 class="page-title">life is short</h1>
            <h1 class="page-title">keep moving</h1>
        </div>
    </div>
    <a class="scroll-down icon-arrow-left" href="#content" data-offset="-45"><span class="hidden">Scroll Down</span></a>
</header>
{% endblock %}


{% block body %}
<main id="content" class="content" role="main">
    {% for blog in blogs %}

    <article class="post">
        <header class="post-header">
            <h2 class="post-title"><a href="{{blog.get_absolute_url}}">{{blog.title}}</a></h2>
        </header>
        <section class="post-excerpt">
            <p><a class="read-more" href="{{blog.get_absolute_url}}">{{blog.snippet}} &raquo;</a></p>
        </section>
        <footer class="post-meta">
            {{blog.author.username}}
            <time class="post-date" datetime='{{blog.add_time|date:"b d, Y"}}'>{{blog.add_time|date:"b d, Y"}}</time>
        </footer>
    </article>

    {% endfor %}

    {% if is_paginated %}
    <nav class="pagination" role="navigation">
        <span class="page-number">Page {{ page_obj.number }} of  {{ page_obj.paginator.num_pages }}</span>

        {% if page_obj.has_previous %}
        <a class="newer-posts" href="/?page={{page_obj.previous_page_number}}">← Newer Posts</a>
        {% endif %}
        {% if page_obj.has_next %}
        <a class="older-posts" href="/?page={{ page_obj.next_page_number }}">Older Posts →</a>
        {% endif %}
    </nav>
    {% endif %}
</main>


{% endblock %}

apps/blog/templates/widget/disqus.html
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//simplisticcode.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

apps/blog/templates/widget/main-nav.html
{% load staticfiles %}
<div class="header">
	<div class="container-fluid">
    	<div class="row">
        	<div class="col-sm-3">
            	<!-- start logo -->
            	<div class="logo">
                	<a href="#"><strong>Simple</strong>Code</a>
                </div>
                <!-- end logo -->
            </div>
            <div class="col-sm-9">
            	<!-- start navigation -->
            	<div class="navigation">
                	<a class="menu-button icon-menu" href="#"><span class="word">Menu</span></a>
                </div>
                <!-- end navigation -->
            </div>
        </div>
    </div>
</div>

apps/blog/templates/widget/share.html
<div class="share">
<wb:share-button appkey="3qwf2q" addition="full" type="button" ralateUid="1697702241" picture_search="false"></wb:share-button>
</div>
<script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js" type="text/javascript" charset="utf-8"></script> 

apps/wedding/templates/wedding_index.html
<!doctype html>
<!--[if IE 7 ]>
<html lang="en-gb" class="isie ie7 oldie no-js"> <![endif]-->
<!--[if IE 8 ]>
<html lang="en-gb" class="isie ie8 oldie no-js"> <![endif]-->
<!--[if IE 9 ]>
<html lang="en-gb" class="isie ie9 no-js"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en-gb" class="no-js">
<!--<![endif]-->
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--[if lt IE 9]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
    <title>我们结婚啦,刘志军&吴长芳</title>
    <meta name="description" content="">
    <meta name="author" content="WebThemez">
    <!--[if lt IE 9]>

    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lte IE 8]>
    <script type="text/javascript" src="http://explorercanvas.googlecode.com/svn/trunk/excanvas.js"></script>

    <![endif]-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link href="{% static 'font/css/font-awesome.min.css' %}" rel="stylesheet">
    <style type='text/css'>
        @font-face {
        font-family: 'NaiYou565988';
        src: url("{% static 'font/fonts/NaiYou.eot' %}");
        src: url("{% static 'font/fonts/NaiYou.eot?#iefix' %}") format('embedded-opentype'),
        url("{% static 'font/fonts/NaiYou.woff' %}") format('woff'),
        url("{% static 'font/fonts/NaiYou.ttf' %}") format('truetype'),
        url("{% static 'font/fonts/NaiYou.svg#NaiYou' %}") format('svg');
        font-weight: normal;
        font-style: normal;

        }
    </style>

 <style type='text/css'>
    @font-face {
font-family: 'minijianshaoer566033';
src: url("{% static 'font/fonts/minijianshaoer.eot' %}");
src: url("{% static 'font/fonts/minijianshaoer.eot?#iefix' %}") format('embedded-opentype'),
     url("{% static 'font/fonts/minijianshaoer.woff' %}") format('woff'),
     url("{% static 'font/fonts/minijianshaoer.ttf' %}") format('truetype'),
     url("{% static 'font/fonts/minijianshaoer.svg#minijianshaoer' %}") format('svg');
    font-weight: normal;
    font-style: normal;
   }
    </style>
</head>

<body>

<nav id="mainNav">
    <div id="menuToggle"><i class="fa fa-bars"></i></div>
    <ul class="menuLinks">
        <li class="active" id="firstLink"><a href="#home" class="scroll-link">主页</a></li>
        <!--<li><a href="#aboutUs" class="scroll-link">关于我们</a></li>-->
        <li><a href="#contactUs" class="scroll-link">邀请</a></li>
    </ul>
</nav>
<!--/.header-->
<div id="#top"></div>
<section id="home">
    <div class="banner-container">
        <div class="container">
            <div class="heading text-center">

                <div class="row">


                    <h2 style='font-family:NaiYou565988'>我们结婚啦！</h2>

                    <h1 style='font-size: 70px;font-family:minijianshaoer566033'>刘志军＆吴长芳</h1>

                    <h3>2016年1月3日 12:00:00</h3>
                    <h4>湖南·娄底·华泰大酒店(火车站斜对面)</h4>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="counter">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="countdown styled"></div>
            </div>
        </div>
    </div>
</section>

<!--<section id="aboutUs">-->
    <!--<div class="container">-->
        <!--<div class="row feature design">-->
            <!--<div class="six columns right">-->
                <!--<h2>我们的故事</h2>-->

                <!--<p></p>-->

                <!--<p></p>-->
            <!--</div>-->
            <!--<div class="six columns feature-media left"><img src="{% static 'images/pic2.JPG' %}" alt=""></div>-->
        <!--</div>-->
    <!--</div>-->
    <!--</div>-->
<!--</section>-->

<section id="contactUs" class="contact-parlex">
    <div class="parlex-back">
        <div class="container">
            <div class="row">
                <div class="heading text-center">
                    <!-- Heading -->
                    <h2>诚挚邀请</h2>

                    <p>世界上最美好的一刻，莫过于和心爱的人牵着彼此的手，编织一段甜蜜的温馨生活。好日子到了，诚邀您参加我们的婚礼，共同见证我们的幸福时刻。</p>
                </div>
            </div>
            <div class="row mrgn30">

                <form method="post" action="/wedding/add_comments/" id="contactfrm" role="form">

                    {% csrf_token %}
                    <div class="col-sm-12">

                        <div class="form-group">
                            <label for="name">姓名</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="输入姓名"
                                   title="Please enter your name (at least 2 characters)">
                        </div>
                        <div class="form-group">
                            <label for="email">电话</label>
                            <input type="text" class="form-control" name="phone" id="email" placeholder="输入电话"
                                   title="Please enter a valid phone number">
                        </div>
                        <div class="form-group">
                            <label for="comments">留言</label>
                            <textarea name="body" class="form-control" id="comments" cols="3" rows="5"
                                      placeholder="输入留言"
                                      title=""></textarea>
                            <button name="submit" type="submit" class="btn btn-lg btn-primary" id="submit">提交
                            </button>
                        </div>

                        <div class="form-group">

                            {% for comment in comments %}
                                <div>{{comment.name}}：{{comment.body}}</div>
                            {% endfor %}

                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!--/.container-->
    </div>
</section>


<a href="#top" class="topHome"><i class="fa fa-chevron-up fa-2x"></i></a>

<script src="{% static 'js/modernizr-latest.js' %}"></script>
<script src="{% static 'js/jquery-1.8.2.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.nav.js' %}" type="text/javascript"></script>
<script src="{% static 'js/waypoints.js' %}"></script>
<script src="{% static 'js/Backstretch.js' %}" type="text/javascript"></script>
<script src="{% static 'js/custom.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/jquery.countdown.js' %}"></script>

</body>
</html>



templates/baidu_verify_3ymtDfPE09.html
3ymtDfPE09